### ISSUE TITLE
Fix trace reading to get variable length

### ISSUE THREAD

**Issue by stweeks-pdx** [stweeks-pdx/ECE585-LLC-GRP1#7]
The trace buffer should get variable length until it sees the `\n` string in the trace parsing of the files. This should then be tested to make sure address of variable length append 0 to the front of the string read if it is less than the expected address length. gets() is not sufficient as it requires a fixed length buffer.

**Comment by Hector-Cardenas** [comment]
Fixed length buffer is ok so long as the buffer is long enough to contain the relevant information. In fact, increasing the buffer length allows for commented trace files, as the parser will ignore anything beyond the initial command and address. Parser already appends 0s through the use of strtoul().
